version: '2'
services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     container_name: wordpress
     volumes:
       - ./src:/var/www/html/
     ports:
       - "8000:80"
     networks:
       - "wp-network"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: mysql_user
       WORDPRESS_DB_PASSWORD: mysql_password
       WORDPRESS_DB_NAME: wordpress